### ISSUE TITLE
its not embedding the styles? using rails 3.1

### ISSUE THREAD

**Issue by papayaah** [Plinq/awesome_mailer#2]
This is my template - http://d.pr/cpWD

But look at source of the html email - http://d.pr/CRBr

my css files aren't embed anywhere, maybe i missed out something? I'm calling the mailer from a rake task if that helps. 

I already had this line on my Gemfile - gem 'awesomemailer'

**Comment by flipsasser** [comment]
Did you modify your mailer to inherit from AwesomeMailer::Base? That's how it knows to apply inline styles!

**Comment by flipsasser** [comment]
Github says it's been 9 months. Did you get this working?
